# Optional: Docker Compose override for additional development tools
# Usage: docker-compose -f docker-compose.yml -f docker-compose.override.yml up

services:
  # MongoDB Admin UI (optional)
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - job-search-network
