version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/app/.env:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped 